spring.application.name=Portfolio
server.port=8082

spring.mongodb.uri=mongodb+srv://ajinkyarepale4554_db_user:Ajinkya45@cluster0.j9nswex.mongodb.net/port?retryWrites=true&w=majority

spring.data.mongodb.write-concern=ACKNOWLEDGED
logging.level.org.springframework.data.mongodb.core=DEBUG

server.servlet.session.persistent=false